# [build]
#   command = "npm install"
#   functions = "netlify/functions"
#   publish = "."

# [functions]
#   node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"

[redirects]
  from = "https://towerdefense.tech/*"
  to = "https://www.towerdefense.tech/:splat"
  status = 301
  force = true